server:
  # The default port on which HTTP connections will be available when starting
  # the Adapter as a standalone application.
  port: 8081

spring:
  datasource:
    # The JDBC URL of the database in which the Adapter tables are located.
    url: jdbc:postgresql://db/dhis2-fhir
    # The username that is required to connect to the database.
    username: dhis-fhir
    # The password that is required to connect to the database.
    password: dhis-fhir

dhis2.fhir-adapter:
  # Configuration of DHIS2 endpoint that is accessed by the adapter.
  endpoint:
    # The base URL of the DHIS2 installation.
    url: http://dhis:8080
    # The API version that should be accessed on the DHIS2 installation.
    api-version: 30
    # Authentication data to access metadata on DHIS2 installation.
    # The complete metadata (organization units, tracked entity types,
    # tracked entity attributes, tracker programs, tracker program stages)
    # must be accessible.
    system-authentication:
      # The username that is used to connect to DHIS2 to access the metadata.
      username: admin
      # The password that is used to connect to DHIS2 to access the metadata.
      password: district
